version: '3.8'

# Define a network for services to communicate reliably
networks:
  itunion_net:
    driver: bridge

services:
  # XE Application Service (Nginx + PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: itunion_app
    ports:
      - "8000:80"
    volumes:
      # Using a relative path is more portable and recommended
      - ./home4/fade3blk/http:/var/www/html
    networks:
      - itunion_net
    # This now waits for the db to be truly healthy before starting
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # MariaDB Database Service with Healthcheck
  db:
    image: mariadb:10.6
    container_name: itunion_db
    environment:
      MYSQL_DATABASE: itu_migration_db
      MYSQL_USER: itunion
      MYSQL_PASSWORD: 7EN3eeZEvMj1Eq
      MYSQL_ROOT_PASSWORD: JKyjggwOCdpRJjYB
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - itunion_net
    # This is the key fix: a healthcheck to ensure the database is ready
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pJKyjggwOCdpRJjYB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  # phpMyAdmin Service (Simplified and reliable)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: itunion_pma
    ports:
      - "8081:80"
    environment:
      # We can go back to this simpler method because of the healthcheck
      PMA_HOST: db
      UPLOAD_LIMIT: 2048M
    networks:
      - itunion_net
    # This also waits for the db to be healthy
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  db_data: